replicaCount: 1

ingress:
  host: gateway.dev.localhost
  tls: false

service:
  port: 1234 # this may break routing completely, why?

backend:
  port: 9999 # changed, but does it break anything, why/why not?

api:
  publicPath: /api/v2 # how does this change our app?
