apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.name" . }}-nginx
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen {{ .Values.service.port }};
      server_name _;
      error_page 404 @sorry;

      location @sorry {
        return 404 "Gateway dead-end, sorry!\n";
      }

      location = /healthz {
        add_header Content-Type text/plain;
        return 200 "Gateway stronk!\n";
      }

      location = / {
        add_header Content-Type text/plain;
        return 200 "Gateway is up for {{ .Release.Name }}\n";
      }

      # TODO: Skip the next parts if api.enabled
      location = {{ .Values.api.publicPath }} {
        return 308 {{ .Values.api.publicPath }}/;
      }

      location ^~ {{ .Values.api.publicPath }}/ {
        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 2s;
        proxy_send_timeout    10s;
        proxy_read_timeout    10s;

        rewrite ^{{ .Values.api.publicPath }}/?(.*)$ /$1 break;

        # TODO: Port to the backend is hardcoded
        proxy_pass http://127.0.0.1:5678/;
      }
    }
