apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-nginx
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
data:
  default.conf: |-
    server {
      listen 80;
      server_name _;

      location = /healthz {
        add_header Content-Type text/plain;
        return 200 "so healthy!\n";
      }

      location = / {
        add_header Content-Type text/plain;
        return 200 "gateway is up for {{ .Release.Name }}\n";
      }

      {{- if .Values.api.enabled }}
      location = {{ .Values.api.publicPath }} {
        return 308 {{ .Values.api.publicPath }}/;
      }

      location ^~ {{ .Values.api.publicPath }}/ {
        proxy_http_version 1.1;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 2s;
        proxy_send_timeout    10s;
        proxy_read_timeout    10s;

        rewrite ^{{ .Values.api.publicPath }}/?(.*)$ /$1 break;

        proxy_pass http://127.0.0.1:{{ .Values.backend.port }}/;
      }
      {{- end }}
    }
