apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  # TODO: Number of replicas is hardcoded!
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        helm.revision: "{{ .Release.Name }}.{{ .Release.Revision }}"
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          # TODO: Get image from values
          image: nginx:alpine
          ports:
            - name: http
              containerPort: 80
          # DONE: mount ConfigMap to /etc/nginx/conf.d/default.conf via subPath
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: nginx-config
              readOnly: true
              subPath: default.conf
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3

        - name: backend
          # TODO: Get image from values
          image: hashicorp/http-echo:1.0.0
          args:
            - "-listen=:5678"
            - "-text={{ .Values.backend.text }}"
          # TODO: template the port number. Remember to be consistent, where else could it be referenced?
          ports:
            - name: backend
              containerPort: 5678

      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "gateway.name" . }}-nginx
            optional: false
          name: nginx-config
