apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        helm.revision: "{{ .Release.Name }}.{{ .Release.Revision }}"
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.nginx }}
          ports:
            - name: http
              containerPort: 80
          # DONE: mount configmap to /etc/nginx/conf.d/default.conf via subPath
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/default.conf
              name: gateway-nginx
              readOnly: true
              subPath: default.conf
          # TODO: add readiness/liveness probe to /healthz

        - name: backend
          image: {{ .Values.image.echo }}
          args:
            - "-listen=:{{ .Values.backend.port }}"
            - "-text={{ .Values.backend.text }}"
          # DONE: add ports
          ports:
            - name: backend
              containerPort: {{ .Values.backend.port }}
          # TODO: add tcpSocket probes

      # TODO: add volumes: configMap gateway-nginx
      volumes:
        - configMap:
            defaultMode: 420
            name: gateway-nginx
            optional: false
          name: gateway-nginx
