replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  nginx: nginx:alpine
  echo: hashicorp/http-echo:1.0.0

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  host: gateway.localhost
  tls: false
  annotations: {}

api:
  enabled: true
  publicPath: /api

backend:
  port: 5678
  text: "Hello from backend"
