apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplest-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simplest-nginx
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        revision: {{ .Release.Revision | quote }} # Makes sure the deployment is restarted on every upgrade
      labels:
        app.kubernetes.io/name: simplest-nginx
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: nginx:{{ .Values.imageTag }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 1
{{ if .Values.overrideHtml }}
          volumeMounts:
            - mountPath: /usr/share/nginx/html/index.html
              name: nginx-default-html
              readOnly: true
              subPath: my.html
      volumes:
      - name: nginx-default-html
        configMap:
          name: simplest-html-configmap
          defaultMode: 420
          optional: false
{{- end -}}
